BulgarianProducers/Controllers/AgriculturalEventsController.cs
using BulgarianProducers.Services.Contracts;
using BulgarianProducers.Services.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulgarianProducers.Controllers
{
    public class AgriculturalEventsController : Controller
    {
        private readonly IEventsService eventsService;

        public AgriculturalEventsController(IEventsService eventsService)
        {
            this.eventsService = eventsService;
        }
        [AllowAnonymous]
        public IActionResult AllEvents([FromQuery] AgriculturalEventQueryModel queryModel)
        {
            var queryResult = this.eventsService.GetEvents(
                 queryModel.SearchTerm,
                 queryModel.Place,
                 queryModel.StartAfter,
                 queryModel.EndBefore,
                 queryModel.CurrentPage,
                 queryModel.Sorting);
            return this.View(queryResult);
        }
        [Authorize]
        public IActionResult Info(int id)
        {
            var @event = this.eventsService.GetEventById(id);
            if (@event == null)
            {
                return this.BadRequest();
            }
            return this.View(@event);
        }

    }
}

BulgarianProducers/Controllers/ProductsController.cs
using AutoMapper;
using BulgarianProducers.Data.Models;
using BulgarianProducers.Models.Products;
using BulgarianProducers.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace BulgarianProducers.Controllers
{
    [Authorize]
    public class ProductsController:Controller
    {
        private readonly IProductService productService;
        private readonly ICategoriesService categoriesService;
        private readonly IMapper mapper;
        private readonly UserManager<User> userManager;
        public ProductsController(
            IProductService productService,
            ICategoriesService categoriesService,
            UserManager<User> userManager,
            IMapper mapper)
        {
            this.productService = productService;
            this.categoriesService = categoriesService;
            this.userManager = userManager;
            this.mapper = mapper;
        }
        [Authorize]
        public IActionResult Details(int id, bool isProduct) 
        {
            if (!isProduct) return this.BadRequest();
            var productToShow = this.productService.GetProduct(id);
            if (productToShow == null) return this.BadRequest();
            
            return this.View(productToShow);
        }
        [Authorize]
        public IActionResult Add() 
        { 
            return this.View(new AddProductFormModel { Categories = this.categoriesService.GetCategories()});
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(AddProductFormModel product)
        {
            var categories = this.categoriesService.GetCategories();
            if (!categories.Any(x=>x.Id == product.CategoryId))
            {
                this.ModelState.AddModelError(nameof(product.CategoryId), "Category does not exist.");
            }
            if (!ModelState.IsValid) 
            {
                product.Categories = categories;
                return View(product);
            }
            var user = await this.userManager.GetUserAsync(this.User);
            product.UserId = user.Id;
            this.productService.AddProduct(product);
            return this.Redirect("/");
        }
        [Authorize]
        public async Task<IActionResult> Delete(int Id, string userId) 
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var currentUserId = user.Id;
            var product = this.productService.GetDataProduct(Id);
            if (currentUserId !=userId) 
            {
                return this.BadRequest();
            }
            if (currentUserId != product.UserId) 
            {
                return this.BadRequest();
            }
            if (product == null) 
            {
                return this.BadRequest();
            }
            this.productService.DeleteProduct(product);
            return this.Redirect("/Home/Mine");
        }
        [Authorize]
        public IActionResult Edit(int id, string userId) 
        {
            var product = this.productService.GetDataProduct(id);
            if (product == null) 
            {
                return this.BadRequest();
            }
            if (product.UserId != userId) 
            {
                return this.Unauthorized();
            }
            var productToEdit = this.mapper.Map<AddProductFormModel>(product);
            productToEdit.Categories = this.categoriesService.GetCategories();
            return this.View(productToEdit); 
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(int id, AddProductFormModel product) 
        {
            if (!this.categoriesService.CheckForCategoryById(product.CategoryId)) 
            {
                this.ModelState.AddModelError(nameof(product.CategoryId), "Category does not exist.");
            }
            if (!this.ModelState.IsValid) 
            {
                var productToEdit = this.mapper.Map<AddProductFormModel>(product);
                productToEdit.Categories = this.categoriesService.GetCategories();
                return this.View(product);
            }
            var user = await this.userManager.GetUserAsync(this.User);
            var currentUserId = user.Id;

            if (product.UserId != currentUserId) 
            {
                return this.Unauthorized();
            }
            this.productService.Edit(id,
                product.Name, 
                product.Price, 
                product.Description, 
                product.CategoryId,
                product.ImageUrl);
            return this.Redirect("/Home/Mine");
        }

    }
}

BulgarianProducers/Controllers/ServicesController.cs
using AutoMapper;
using BulgarianProducers.Data.Models;
using BulgarianProducers.Models.Services;
using BulgarianProducers.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BulgarianProducers.Controllers
{
    [Authorize]
    public class ServicesController : Controller
    {
        private readonly IServicesService servicesService;
        private readonly IServiceTypeService serviceTypeService;
        private readonly UserManager<User> userManager;
        private readonly IMapper mapper;
        public ServicesController(
            IServicesService servicesService,
            IServiceTypeService serviceTypeService,
            UserManager<User> userManager,
            IMapper mapper)
        {
            this.servicesService = servicesService;
            this.serviceTypeService = serviceTypeService;
            this.userManager = userManager;
            this.mapper = mapper;
        }
        [HttpGet]
        public IActionResult Add()
        {
            return this.View(new AddServiceFormModel { ServiceTypes = this.serviceTypeService.GetServiceTypes() });
        }
        [HttpPost]
        public async Task<IActionResult> Add(AddServiceFormModel service)
        {
            if (!serviceTypeService.CheckForServiceTypeById(service.ServiceTypeId))
            {
                this.ModelState.AddModelError(nameof(service.ServiceTypeId), "ServiceType does not exist.");
            }
            if (!ModelState.IsValid)
            {
                service.ServiceTypes = this.serviceTypeService.GetServiceTypes();
                return this.View(service);
            }
            var user = await this.userManager.GetUserAsync(this.User);
            service.UserId = user.Id;
            this.servicesService.AddService(service);
            return this.Redirect("/Home/All");
        }
        public IActionResult Details(int id, bool isProduct)
        {

            if (isProduct) return this.BadRequest();
            var serviceToShow = servicesService.GetService(id);
            if (serviceToShow == null) return this.BadRequest();


            return this.View(serviceToShow);
        }
        public IActionResult Edit(int id, string userId)
        {
            var service = this.servicesService.GetDataService(id);
            if (service == null)
            {
                return this.BadRequest();
            }
            if (service.UserId != userId)
            {
                return this.Unauthorized();
            }
            var serviceToEdit = this.mapper.Map<AddServiceFormModel>(service);
            serviceToEdit.ServiceTypes = this.serviceTypeService.GetServiceTypes();
            return this.View(serviceToEdit);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, AddServiceFormModel service)
        {
            if (!this.serviceTypeService.CheckForServiceTypeById(service.ServiceTypeId))
            {
                this.ModelState.AddModelError(nameof(service.ServiceTypeId), "Service does not exist.");
            }
            if (!this.ModelState.IsValid)
            {
                var serviceToEdit = this.mapper.Map<AddServiceFormModel>(service);
                serviceToEdit.ServiceTypes = this.serviceTypeService.GetServiceTypes();
                return this.View(service);
            }
            var user = await this.userManager.GetUserAsync(this.User);
            var currentUserId = user.Id;

            if (service.UserId != currentUserId)
            {
                return this.Unauthorized();
            }
            this.servicesService.Edit(id,
                service.Name,
                service.Price,
                service.AdditionalInformation,
                service.ServiceTypeId,
                service.ImageUrl,
                service.TimeNeeded);
            return this.Redirect("/Home/Mine");
        }
        public async Task<IActionResult> Delete(int Id, string userId)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var currentUserId = user.Id;
            var service = this.servicesService.GetDataService(Id);
            if (currentUserId != userId)
            {
                return this.BadRequest();
            }
            if (currentUserId != service.UserId)
            {
                return this.BadRequest();
            }
            if (service == null)
            {
                return this.BadRequest();
            }
            this.servicesService.DeleteProduct(service);
            return this.Redirect("/Home/Mine");

        }
    }
}

BulgarianProducers/Views/Shared/_AllEventsPartial.cshtml
@model List<AgriculturalEventInfoModel>
@{
    bool isAdmin = this.User.IsInRole("Admin");
    string adminArea = "Admin";
    var i = 0;
}

@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Име</th>
                <th scope="col">Къде се провежда</th>
                <th scope="col">Започва на</th>
                <th scope="col">Приключва</th>
                <th scope="col">Информация</th>>
            </tr>
        </thead>
        <tbody>
            @foreach (var element in Model)
            {
                <tr>
                    <th scope="row">@i</th>
                    <td>@element.Name</td>
                    <td>@element.Place</td>
                    <td>@element.StartDate</td>
                    <td>@element.EndDate</td>
                    <td>
                        <a asp-area="" asp-controller="AgriculturalEvents" asp-action="Info" class="btn btn-primary" asp-route-id="@element.Id"><i class="fas fa-search"></i></a>
                        @if (isAdmin)
                        {
                            <a asp-area="@adminArea" asp-controller="AgriculturalEvents" asp-action="Edit" class="btn btn-warning" asp-route-id="@element.Id"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                            <a asp-area="@adminArea" asp-controller="AgriculturalEvents" asp-action="Delete" class="btn btn-danger" asp-route-id="@element.Id"><i class="fas fa-trash"></i></a>
                        }


                    </td>
                </tr>
                i++;
            }
        </tbody>
    </table>
    @if (isAdmin)
    {
        <a class="nav-link btn-primary btn-lg" asp-area="@adminArea" asp-controller="AgriculturalEvents" asp-action="Add">Добави ново събитие!</a>
    }
}

BulgarianProducers/Views/Shared/_Layout.cshtml
@{
    var area = "";
    if (this.User.IsInRole("Admin"))
    {
        area = "Admin";
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Българските производители</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header id="header">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Българския пазар</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="dropdown col-2">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Добави
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Add">Продукт</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Add">Услуга</a>
                                </div>
                            </li>
                            <li class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Виж
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="All">Всички</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Mine">Моите обяви</a>
                                    <a class="nav-link text-dark" asp-area="@area" asp-controller="AgriculturalEvents" asp-action="AllEvents">Събития</a>
                                </div>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Chat">Лафче</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div id="sidebar">
        @RenderSection("SideBar", required:false)
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - BulgarianProducers
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/lib/bootstrap/dist/css"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/d8f5e53c07.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>